# Generated by Django 2.1.11 on 2019-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("REDIS", "Redis")], default="sqs", max_length=32
                    ),
                ),
                ("ep_id", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Transformer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
    ]
