# Generated by Django 2.1.7 on 2019-08-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("engine", "0003_appconfiguration")]

    operations = [
        migrations.RenameField(
            model_name="appconfiguration",
            old_name="aws_dns_auth",
            new_name="some_config_option",
        )
    ]
