# Generated by Django 2.1.11 on 2019-11-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("engine", "0004_auto_20190830_1525")]

    operations = [migrations.DeleteModel(name="SomeModel")]
